src/english/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import Index, add_site, select2

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^select2/$', select2, name='select2'),
    url(r'^site/add/$', add_site, name='site_add'),
]

src/lang_resources/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from sitemap import StaticViewSitemap
import english.urls


sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^', include(english.urls, namespace='english')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^select2/', include('django_select2.urls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/english/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils.text import slugify
from sorl.thumbnail import ImageField, get_thumbnail
from transliterate import translit


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(verbose_name='Slug', unique=True, max_length=100)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Languages(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class PricePolicy(models.Model):
    text = models.CharField(max_length=100)
    help = models.TextField(max_length=500, blank=True, null=True)
    css_class = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.text


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(verbose_name='Slug', unique=True, max_length=100, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super(Tag, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Site(models.Model):
    link = models.URLField(max_length=500, help_text="Example: https://example.com")
    name = models.CharField(max_length=500, blank=True)
    description = models.TextField(max_length=500)
    tags = models.ManyToManyField(Tag, blank=True, related_name='sites')
    price_policy = models.ForeignKey(PricePolicy)
    is_recommend = models.BooleanField("Выбор редакции", default=False)
    image = ImageField(upload_to="english/site_images", blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="site", blank=True)
    languages = models.ManyToManyField(Languages, related_name="site")
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=5)
    moderated = models.BooleanField("Модерация", default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('rating', )

    def sort_description(self):
        return self.description[:50] + ".."

    def show_preview(self):
        if self.image:
            im = get_thumbnail(self.image, '60x60', crop='center', quality=99)
            return '<img src="%s" />' % im.url

    show_preview.allow_tags = True
    show_preview.short_description = 'Image preview'

src/english/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.contrib.auth import get_user_model


from .models import Site

User = get_user_model()


class SiteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SiteForm, self).__init__(*args, **kwargs)
        self.fields['price_policy'].empty_label = None

    class Meta:
        model = Site
        exclude = ("languages", "rating")
        widgets = {
            'price_policy': forms.RadioSelect,
        }

src/english/views.py
# -*- coding: utf-8 -*-
import json
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.http import JsonResponse

from .forms import SiteForm
from .models import Site, Category, Tag


class Index(TemplateView):
    template_name = "english/index.html"

    # @method_decorator(cache_page(60*60*5))
    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["sites"] = Site.objects.all()
        ctx["tags"] = Tag.objects.all()
        ctx["form"] = SiteForm()
        return self.render_to_response(ctx)


def add_site(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SiteForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return JsonResponse({"status": True})
    else:
        form = SiteForm()
    return render(request, "english/site_add_form.html", {"form": form})


def select2(request):
    tags = Tag.objects.all()
    results = [{'id': index, 'text': value} for (index, value) in enumerate(tags)]
    return JsonResponse({'err': 'nil', 'results': results})

src/templates/english/base.html
{% load staticfiles %}
{% load thumbnail %}


<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="ru"> <!--<![endif]-->

<head>

	<meta charset="utf-8">

	<title>{% block title %}Language Resources: подборка лучших материалов для изучения иностранных языков{% endblock %}</title>
	<meta name="description" content="Лучшая подборка материалов для эффективного изучения иностранных языков онлайн.">
    <meta name="title" content="Language Resources: подборка лучших материалов для изучения иностранных языков">
    <meta Name="keywords" content="Ресурсы для изучения языков,материалы для обучения онлайн,Английский язык онлайн">
    <link rel="icon" href="{% static "english/img/favicon.png" %}" type="image/x-icon">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% block styles %}
        <link rel="stylesheet" href="{% static "english/libs/magnific/magnific-popup.css" %}">
    	<link rel="stylesheet" href="{% static "english/css/fonts.css" %}">
        <link rel="stylesheet" href="{% static "english/css/main.css" %}">
        <link rel="stylesheet" href="{% static "english/css/media.css" %}">
    {% endblock styles %}

    {% block extrahead %}{% endblock extrahead %}

    	<!--[if lt IE 9]>
	<script src="libs/html5shiv/es5-shim.min.js"></script>
	<script src="libs/html5shiv/html5shiv.min.js"></script>
	<script src="libs/html5shiv/html5shiv-printshiv.min.js"></script>
	<script src="libs/respond/respond.min.js"></script>
	<![endif]-->
    {% block scripts %}
        <script src="{% static "english/libs/modernizr/modernizr.js" %}"></script>
        <script src="{% static "english/libs/jquery/jquery-1.11.2.min.js" %}"></script>
        <script src="{% static "english/libs/magnific/jquery.magnific-popup.min.js" %}"></script>

    	<script src="{% static "english/js/common.js" %}"></script>
    {% endblock scripts %}

    {% if not debug %}
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter38918505 = new Ya.Metrika({
                            id:38918505,
                            clickmap:true,
                            trackLinks:true,
                            accurateTrackBounce:true,
                            webvisor:true,
                            trackHash:true
                        });
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/38918505" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
    {% endif %}
</head>

<body>
{% block content %}
{% endblock %}

</body>
</html>

src/templates/english/index.html
{% extends "english/base.html" %}

{% load staticfiles %}
{% load thumbnail %}


{% block content %}
    <header>
        <div class="container">
            <div class="logo-wrap"><h1><a href="#"><span>Language</span>Resources</a> </h1><img src="{% static "english/img/logo.png" %}" alt=""></div>
            <h2>Лучшие Ресурсы <br>Для Изучения Английского Языка</h2>
            <p class="subtitle">Здесь собраны все самые полезные сайты для изучения английского языка. <br> Вы имеете прекрасную возможность выбрать то, что подходит именно Вам.</p>
        </div>
    </header>
    <div class="button">
        <div class="sticky-anchor2"></div>
        <button class="filtre-btn">Меню</button>
    </div>


    <div class="container">
        <div class="main-contant">
            {% for site in sites %}
                <div class="site-wrap" data-categories="{% for category in site.tags.all %}{{ category.slug }} {% endfor %}">
                    <div class="thumb-wrap">
                        <a href="{{ site.link }}" target="_blank">
                            {% thumbnail site.image "600x600" crop="top" as im %}
                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ site.name }}">
                            {% empty %}
                            {% endthumbnail %}

                        </a>
                    </div>
                    <div class="info-wrap">
                        <h4><a href="{{ site.link }}" target="_blank">{{ site.name }}</a></h4>
                        <p>{{ site.description }}</p>
                        <span class="worth-info {{ site.price_policy.css_class }}">{{ site.price_policy.text }}</span>
                        <div class="tags">
                            {% for tag in site.tags.all %}
                                <span>#{{ tag }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <aside>
            <div class="sticky-anchor"></div>
            <div class="menu-wrap aside-hide" id="aside-menu">
                <span id="close-menu"></span>
                <p class="search-title">Фильтр по навыкам:</p>
                <ul class="skills">
                    <li class="toggle main" data-slug="all"><input type="checkbox" class="checkbox" id="checkbox0" checked><label for="checkbox0">Показать все ресурсы</label></li>
                    {% for tag in tags %}
                        <li class="toggle items" data-slug="{{ tag.slug }}"><input type="checkbox" class="checkbox" id="checkbox{{ forloop.counter }}">
                            <label for="checkbox{{ forloop.counter }}">{{ tag.name }}</label>
                        </li>
                    {% endfor %}
                </ul>
{#                <a href="#form-popup" class="popup offer-resourse">Предложить ресурс</a>#}
                <div class="hidden">
                    <div id="form-popup">
                        {% include "english/site_add_form.html" %}
                    </div>
                </div>
            </div>
        </aside>
    </div>
    <footer>
        <p>©Lang-resources.com {% now "Y" %}</p>
        <p>Обратная связь: info@lang-resources.com</p>
    </footer>
{% endblock %}

src/templates/english/site_add_form.html
<form action="{% url "english:site_add" %}" method="post" id="offer-form">
    {% csrf_token %}
    <h3>Предложите сайт</h3>
    <label for="{{ form.link.id_for_label }}">Ссылка на сайт</label>{{ form.link }}
    {{ form.link.errors }}
    <label for="{{ form.description.id_for_label }}">Описание сайта</label>{{ form.description }}
    {{ form.description.errors }}
    <div class="worth">
        {{ form.price_policy }}
{#                            <div class="checked-wrap"><input type="radio"  name="group1" checked> <label for="">Бесплатный</label></div>#}
    </div>
    {{ form.price_policy.errors }}
    <button id="send" type="submit">Предложить</button>
</form>

{#5fpvYEgl4u4Dd2SSmFhhMUMz0CNEHXX7iLlDQocfMykVWLkUV29Em2IYccSpiehU#}

src/templates/english/test.html
test.html